### ISSUE TITLE
url decode not working for forms post that contain spaces.

### ISSUE THREAD

**Issue by fmuntean** [Azure/azure-c-shared-utility#645] opened 2023-10-19 01:39 UTC
when trying to use the library to decode the url encoded string produced by a form post I get invalid string format.
I think is because the SPACE character is not correctly supported.

**Comment by ericwol-msft** [comment] 2023-10-19 17:40
please add more info

**Comment by fmuntean** [comment] 2023-10-21 13:20
seems that is not supporting the '+' as a space.
html forms encodes the space as a '+' instead of %20 and this library does not supports it.
"URL encoding normally replaces a space with a plus (+) sign or with %20."

**Comment by CIPop** [comment] 2023-10-23 17:31
Our library is a (partial) implementation of RFC [3986](https://www.rfc-editor.org/rfc/rfc3986). This URI encoding is mandatory and must not change.

Our library does not support the encoding required by `application/x-www-form-urlencoded` which is different.

For a discussion on the subject, please see https://stackoverflow.com/questions/2678551/when-should-space-be-encoded-to-plus-or-20.


Closing as not supported, by design.

**Closed by CIPop** 2023-10-23 17:31 UTC
